# Generated by Django 5.0 on 2024-01-20 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=2000)),
                ('client', models.CharField(max_length=2000)),
                ('date', models.DateField()),
                ('description', models.TextField()),
                ('image1', models.ImageField(upload_to='Images/')),
                ('image2', models.ImageField(upload_to='Images/')),
                ('image3', models.ImageField(upload_to='Images/')),
                ('image4', models.ImageField(upload_to='Images/')),
                ('image5', models.ImageField(upload_to='Images/')),
                ('slug', models.SlugField()),
                ('link', models.URLField()),
            ],
        ),
    ]
