# Generated by Django 5.0 on 2024-01-20 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image6',
            field=models.ImageField(null=True, upload_to='Images/'),
        ),
        migrations.AddField(
            model_name='project',
            name='image7',
            field=models.ImageField(null=True, upload_to='Images/'),
        ),
    ]
