# Generated by Django 5.0 on 2024-01-24 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_certificates_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='keyword1',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='keyword2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='keyword3',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
